name: Notify deps2.dev of New Version

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow on pushing tags that start with 'v'

jobs:
  notify-deps2dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read version
      id: version
      run: echo "::set-output name=VERSION::$(cat version.txt)"

    - name: Get current date
      id: date
      run: echo "::set-output name=DATE::$(date +'%Y-%m-%d')"

    - name: Notify deps2.dev
      env:
        DEPS2DEV_URL: "https://deps.dev/newVersion" # Replace with your actual deps2.dev URL
      run: |
        curl -X POST $DEPS2DEV_URL \
          -H "Content-Type: application/json" \
          -d '{
            "package": "VeriTax",
            "version": "${{ steps.version.outputs.VERSION }}",
            "release_date": "${{ steps.date.outputs.DATE }}"
          }'

    - name: Check notification status
      run: |
        if [ $? -eq 0 ]; then
          echo "Successfully notified deps2.dev of new version ${{ steps.version.outputs.VERSION }}"
        else
          echo "Failed to notify deps2.dev"
          exit 1
        fi
